output "names" {
  description = "Map of all resource names generated by the naming convention"
  value       = local.names
}

# Convenience outputs for most common resources
output "resource_group" {
  description = "Resource Group name"
  value       = local.names.resource_group
}

output "virtual_network" {
  description = "Virtual Network name"
  value       = local.names.virtual_network
}

output "key_vault" {
  description = "Key Vault name"
  value       = local.names.key_vault
}

output "storage_account" {
  description = "Storage Account name (no dashes, max 24 chars)"
  value       = local.names.storage_account
}

output "kubernetes_cluster" {
  description = "AKS Cluster name"
  value       = local.names.kubernetes_cluster
}

output "container_registry" {
  description = "Container Registry name (no dashes, lowercase)"
  value       = local.names.container_registry
}

output "log_analytics_workspace" {
  description = "Log Analytics Workspace name"
  value       = local.names.log_analytics_workspace
}

output "application_insights" {
  description = "Application Insights name"
  value       = local.names.application_insights
}

# Expose normalized inputs for reference/debugging
output "context" {
  description = "Normalized naming context (useful for debugging)"
  value = {
    project      = local.project
    service_name = local.workload
    environment  = local.environment
    region       = local.region
    suffix       = local.suffix
    base_name    = local._base_standard
  }
}
