output "names" {
  description = "Map of all resource names generated by the naming convention"
  value       = local.names
}

output "region" {
  description = "value"
  value = local.region
}


# ─── General ─────────────────────────────────────────────────────────────────
output "resource_group" {
  description = "Resource Group name"
  value       = local.names.resource_group
}

# ─── AI + Machine Learning ───────────────────────────────────────────────────
output "machine_learning_workspace" {
  description = "Azure Machine Learning workspace name"
  value       = local.names.machine_learning_workspace
}

output "openai_account" {
  description = "Azure OpenAI account name"
  value       = local.names.openai_account
}

output "ai_search" {
  description = "AI Search name"
  value       = local.names.ai_search
}

# ─── Analytics and IoT ───────────────────────────────────────────────────────
output "data_factory" {
  description = "Azure Data Factory name"
  value       = local.names.data_factory
}

output "databricks_workspace" {
  description = "Azure Databricks workspace name"
  value       = local.names.databricks_workspace
}

output "eventhub_namespace" {
  description = "Event Hubs namespace name"
  value       = local.names.eventhub_namespace
}

output "eventhub" {
  description = "Event Hub name"
  value       = local.names.eventhub
}

output "synapse_workspace" {
  description = "Azure Synapse Analytics workspace name"
  value       = local.names.synapse_workspace
}

# ─── Compute and Web ─────────────────────────────────────────────────────────
output "virtual_machine" {
  description = "Virtual Machine name"
  value       = local.names.virtual_machine
}

output "virtual_machine_scale_set" {
  description = "Virtual Machine Scale Set name"
  value       = local.names.virtual_machine_scale_set
}

output "app_service_plan" {
  description = "App Service Plan name"
  value       = local.names.app_service_plan
}

output "app_service" {
  description = "App Service (Web App) name"
  value       = local.names.app_service
}

output "function_app" {
  description = "Function App name"
  value       = local.names.function_app
}

output "static_web_app" {
  description = "Static Web App name"
  value       = local.names.static_web_app
}

# ─── Containers ──────────────────────────────────────────────────────────────
output "kubernetes_cluster" {
  description = "AKS Cluster name"
  value       = local.names.kubernetes_cluster
}

output "container_registry" {
  description = "Container Registry name (no dashes, max 50 chars)"
  value       = local.names.container_registry
}

output "container_app" {
  description = "Container App name"
  value       = local.names.container_app
}

output "container_app_environment" {
  description = "Container App Environment name"
  value       = local.names.container_app_environment
}

# ─── Databases ───────────────────────────────────────────────────────────────
output "sql_server" {
  description = "Azure SQL Server name"
  value       = local.names.sql_server
}

output "sql_database" {
  description = "Azure SQL Database name"
  value       = local.names.sql_database
}

output "postgresql_flexible_server" {
  description = "PostgreSQL Flexible Server name"
  value       = local.names.postgresql_flexible_server
}

output "cosmosdb_account" {
  description = "Cosmos DB account name"
  value       = local.names.cosmosdb_account
}

output "redis_cache" {
  description = "Azure Cache for Redis name"
  value       = local.names.redis_cache
}

# ─── Developer Tools ─────────────────────────────────────────────────────────
output "app_configuration" {
  description = "App Configuration store name"
  value       = local.names.app_configuration
}

# ─── Integration ─────────────────────────────────────────────────────────────
output "api_management" {
  description = "API Management service name"
  value       = local.names.api_management
}

output "servicebus_namespace" {
  description = "Service Bus namespace name"
  value       = local.names.servicebus_namespace
}

output "logic_app" {
  description = "Logic App name"
  value       = local.names.logic_app
}

# ─── Management and Governance ───────────────────────────────────────────────
output "log_analytics_workspace" {
  description = "Log Analytics Workspace name"
  value       = local.names.log_analytics_workspace
}

output "application_insights" {
  description = "Application Insights name"
  value       = local.names.application_insights
}

output "recovery_services_vault" {
  description = "Recovery Services Vault name"
  value       = local.names.recovery_services_vault
}

# ─── Networking ──────────────────────────────────────────────────────────────
output "virtual_network" {
  description = "Virtual Network name"
  value       = local.names.virtual_network
}

output "subnet" {
  description = "Subnet name"
  value       = local.names.subnet
}

output "network_security_group" {
  description = "Network Security Group name"
  value       = local.names.network_security_group
}

output "application_gateway" {
  description = "Application Gateway name"
  value       = local.names.application_gateway
}

output "private_endpoint" {
  description = "Private Endpoint name"
  value       = local.names.private_endpoint
}

output "firewall" {
  description = "Azure Firewall name"
  value       = local.names.firewall
}

output "nat_gateway" {
  description = "NAT Gateway name"
  value       = local.names.nat_gateway
}

output "public_ip" {
  description = "Public IP address name"
  value       = local.names.public_ip
}

# ─── Security ────────────────────────────────────────────────────────────────
output "key_vault" {
  description = "Key Vault name"
  value       = local.names.key_vault
}

output "user_assigned_identity" {
  description = "User Assigned Managed Identity name"
  value       = local.names.user_assigned_identity
}

output "bastion_host" {
  description = "Azure Bastion name"
  value       = local.names.bastion_host
}

# ─── Storage ─────────────────────────────────────────────────────────────────
output "storage_account" {
  description = "Storage Account name (no dashes, max 24 chars)"
  value       = local.names.storage_account
}

output "backup_vault" {
  description = "Backup Vault name"
  value       = local.names.backup_vault
}

# ─── Debug ───────────────────────────────────────────────────────────────────
output "context" {
  description = "Normalized naming context (useful for debugging)"
  value = {
    project     = local.project
    workload    = local.workload
    environment = local.environment
    region      = local.region
    suffix      = local.suffix
    base_name   = local._base_standard
  }
}
